server:
  port: 8001
spring:
  application:
    name: simple-react-agent
  ai:
    dashscope:
      api-key: sk-fddc34d562ab49059c2d35c5fb1e0cc6
  data:
    redis:
      host: localhost
      port: 6379