server:
  port: 8001
  # 防止大模型输出乱码
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: Agentic-RAG
  # spring-ai-alibaba config
  ai:
    dashscope:
      api-key: sk-fddc34d562ab49059c2d35c5fb1e0cc6
      # 对话模型
      chat:
        options:
          model: qwen3-max
      # 向量化模型
      embedding:
        options:
          model: text-embedding-v3
      # 向量重排模型（混合搜索优化结果用）
      rerank:
        options:
          model: qwen3-rerank
    vectorstore:
      redis:
        index-name: Agentic-RAG-index
        prefix: Agentic-RAG-prefix
        initialize-schema: true
  data:
    redis:
      host: localhost
      port: 6379